# Generated by Django 4.0.4 on 2022-05-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
