# Generated by Django 4.0.4 on 2022-05-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_variable_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
